export const ErrorCodes = {
  AUTH_STEAM_TIMEOUT_GET_TOKEN: 'AUTH-STEAM-GET-TOKEN-0002',
  AUTH_STEAM_PLAYER_NOT_FOUND: 'AUTH-STEAM-LOGIN-0001',
  AUTH_STEAM_USER_NOT_FOUND: 'AUTH-STEAM-LOGIN-0002',
} as const;
